version: '3.8'

services:
  documentprocessor.api:
    image: ${DOCKER_REGISTRY-}documentprocessorapi
    build:
      context: .
      dockerfile: DocumentProcessor.API/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - documents_data:/app/documents
      - logs_data:/app/logs
    depends_on:
      - documentprocessor.master
      - documentprocessor.worker
      - rabbitmq
      - mysql

  documentprocessor.master:
    image: ${DOCKER_REGISTRY-}documentprocessormaster
    build:
      context: .
      dockerfile: DocumentProcessor.Master/Dockerfile
    volumes:
      - logs_data:/app/logs
    depends_on:
      - rabbitmq
      - mysql

  documentprocessor.worker:
    image: ${DOCKER_REGISTRY-}documentprocessorworker
    build:
      context: .
      dockerfile: DocumentProcessor.Worker/Dockerfile
    volumes:
      - documents_data:/app/documents
      - logs_data:/app/logs
    depends_on:
      - rabbitmq
      - mysql
  
  documentprocessor.writer:
    image: ${DOCKER_REGISTRY-}documentprocessorwriter
    build:
      context: .
      dockerfile: DocumentProcessor.Writer/Dockerfile
    volumes:
      - logs_data:/app/logs
    depends_on:
      - rabbitmq
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mysql:
    image: mysql:8.0
    container_name: documentprocessor_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: documentprocessor
      MYSQL_USER: dpuser
      MYSQL_PASSWORD: dppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  documents_data:
  logs_data: